name: Changelog
# on:
#   release:
#     types: [created, published]
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "✏️ Generate release changelog"
        uses: janheinrichmerker/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
