name: Changelog
on:
  release:
    types:
      - created
      - published
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "✏️ Generate release changelog"
        uses: janheinrichmerker/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: "./changelog.md"

      - name: Commit changelog
        run: |
          git config --local user.name "Your Name"  # Replace with your name
          git config --local user.email "your-email@example.com"  # Replace with your email
          git add changelog.md
          git commit -m "Update changelog"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for authentication
