name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write # To be able to create a release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "✏️ Generate release changelog"
        uses: janheinrichmerker/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          body_path: ${{ github.workspace }}/CHANGELOG.md
          repository: CHR-onicles/release-based-workflow
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          # token: ${{ secrets.CUSTOM_TOKEN }}
